### PR TITLE
Upgrade TodoMVC example to scalajs-react 1.0.0-RC2

### PR DESCRIPTION
**Pull request by glmars**
I upgraded TodoMVC example to scalajs-react 1.0.0-RC2 and diode 1.1.2-SNAPSHOT.

Could you merge this and update your pull request to original suzaku-io/diode?

### CODE REVIEW

**Comment by alonsodomin** [comment]
Hi @glmars. Thanks for that, I just rebased this branch from the upstream diode, would you mind solving the small conflict in the `README.md` file?

**Comment by glmars** [comment]
@alonsodomin, thank you for your quick response.

I resolved conflict in the README.md file by using github interface and github created new merge commit.
Is it right? It is my first pull request, please, correct me if I make something wrong.

**Comment by alonsodomin** [comment]
yeah, it should be alright, this is not the upstream project anyway. if the original PR gets accepted the commits will be smashed into one

**Comment by glmars** [comment]
Thank you for clarifying. I'll look forward to accepting of the original PR.

**Pull request merged**
